version: '3'

services:
  
  nest:
    build: ./nest-api
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3000:3000
    volumes:
      - ./nest-api:/home/node/app

  react:
    build: ./react-app
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3001:3000
    volumes:
      - ./react-app:/home/node/app
    